### ISSUE TITLE
[WARNING] The POM for org.apache.logging.log4j:log4j-changelog:jar:0.5.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

### ISSUE THREAD

**Issue by garydgregory** [apache/logging-log4j-tools#84]
## Description

Running the plugin with 'mvn clean verify' for Apache Log4j 2.22.0 RC1 emits a warning:

[WARNING] The POM for org.apache.logging.log4j:log4j-changelog:jar:0.5.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

## Configuration

**Version:**
0.5.0

**Operating system:**
Microsoft Windows [Version 10.0.19045.3570]

**JDK:** 
openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment Temurin-11.0.20+8 (build 11.0.20+8)
OpenJDK 64-Bit Server VM Temurin-11.0.20+8 (build 11.0.20+8, mixed mode)

## Logs

```
[INFO] --- log4j-changelog:0.5.0:export (export-changelog) @ log4j-bom ---
[WARNING] The POM for org.apache.logging.log4j:log4j-changelog:jar:0.5.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
exported 54 release directories: ..., `C:\tmp\test\src\changelog\2.22.0`
exporting upcoming release directory: `C:\tmp\test\src\changelog\.2.x.x`
```

## Reproduction

Run `mvn clean verify` on Apache Log4j 2.22.0 RC1.

**Comment by vy** [comment]
`log4j-tools-bom:0.5.0` uses `logging-parent:10.1.1`, which removes the `parent` while flattening the BOM, though it shouldn't. This issue is fixed in `logging-parent:10.2.0` via apache/logging-parent#37. Hence, `log4j-tools-bom:0.6.0`, which uses `logging-parent:10.4.0`, will have a BOM with a valid `parent`.

Once `log4j-tools-bom:0.6.0` is out, we will use it in `logging-parent:10.5.0`, which we will use it in `log4j-tools-bom:0.7.0`, which won't have this `WARNING` anymore.
